### ISSUE TITLE
Question about API capabilities

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [amazon-connect/amazon-connect-chat-ios-examples#2]
Hello,

Does Amazon Connect iOS SDK provide APIs to login as an agent, change their online status, receive and send chats?

Basically do the operations an agent normally does but through our own custom front-end.

Is this possible at this time?

**Comment by efh365** [comment]
Hi. Sorry but no, at this time the iOS SDK does not have agent functionality.
